import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { content, isLocale, locales, routes, serviceRoutes, href, type Route } from '@/lib/content';
import { Header, Footer, Home, ServicePage, About, ContactPage, ContactBand, ServiceGrid } from '@/components/site';
type Props={params:Promise<{lang:string;slug?:string[]}>};
async function resolve(params:Props['params']) {const {lang,slug=[]}=await params;const route=slug.join('/');if(!isLocale(lang)||!routes.includes(route as Route))notFound();return {lang,route:route as Route};}
export function generateStaticParams(){return routes.map(route=>({slug:route?[route]:[]}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {lang,route}=await resolve(params);const c=content[lang];const index=serviceRoutes.findIndex(r=>r===route);const title=index>=0?`${c.services[index].tag} | Akemis`:route==='about'?`${c.nav[3]} | Akemis`:route==='contact'?`${c.nav[4]} | Akemis`:`Akemis | ${c.footer}`;const description=index>=0?c.services[index].description:route==='about'?c.aboutText:route==='contact'?c.contactText:c.sub;return {metadataBase:new URL('https://akemis.com'),title,description,alternates:{canonical:href(lang,route),languages:{...Object.fromEntries(locales.map(l=>[l,href(l,route)])),'x-default':href('en',route)}},openGraph:{title,description,url:href(lang,route),type:'website',siteName:'Akemis',locale:{en:'en_GB',es:'es_ES',fr:'fr_FR'}[lang],images:[{url:'/images/hong-kong-skyline.jpg',alt:c.photo}]},twitter:{card:'summary_large_image',title,description,images:['/images/hong-kong-skyline.jpg']}};}
export default async function Page({params}:Props){const {lang,route}=await resolve(params);const index=serviceRoutes.findIndex(r=>r===route);return <><Header lang={lang} route={route}/><main id="main">{route===''?<Home lang={lang}/>:index>=0?<ServicePage lang={lang} index={index}/>:route==='about'?<><About lang={lang} full/><ServiceGrid lang={lang}/><ContactBand lang={lang}/></>:<ContactPage lang={lang}/>}</main><Footer lang={lang}/></>;}
