import Link from 'next/link';
import Image from 'next/image';
import { ContactForm } from './contact-form';
import { content, locales, serviceRoutes, href, type Locale, type Route, type Copy } from '@/lib/content';

export function Header({lang, route}: {lang: Locale; route: Route}) {
 const c=content[lang];
 const links=[...serviceRoutes,'about','contact'];
 return <><a className="skip-link" href="#main">{c.skip}</a><header className="site-header"><div className="shell header-inner">
  <Link href={href(lang)} aria-label="Akemis" className="wordmark">akemis<span>®</span></Link>
  <nav className="desktop-nav" aria-label={c.menu}>{links.map((r,i)=><Link key={r} href={href(lang,r)} aria-current={route===r?'page':undefined}>{c.nav[i]}{i===4&&<span aria-hidden="true"> ↗</span>}</Link>)}</nav>
  <nav className="languages" aria-label={c.language}>{locales.map(l=><Link key={l} href={href(l,route)} hrefLang={l} lang={l} aria-label={{en:'English',es:'Español',fr:'Français'}[l]} aria-current={lang===l?'page':undefined}>{l.toUpperCase()}</Link>)}</nav>
  <details className="mobile-menu"><summary>{c.menu} <span aria-hidden="true">＋</span></summary><nav aria-label={c.menu}>{links.map((r,i)=><Link key={r} href={href(lang,r)}>{c.nav[i]}</Link>)}</nav></details>
 </div></header></>;
}
export function Footer({lang}: {lang: Locale}) {const c=content[lang];return <footer className="site-footer"><div className="shell"><div className="footer-top"><Link href={href(lang)} className="wordmark">akemis<span>®</span></Link><p>{c.footer}</p><a href="mailto:contact@akemis.com">contact@akemis.com ↗</a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Akemis · Hong Kong</span><span>{c.legal}: <Link href="/creators/privacy">Privacy</Link> / <Link href="/creators/terms">Terms</Link> <span lang="en">(English)</span></span></div></div></footer>}
export function ServiceGrid({lang}: {lang: Locale}) {const c=content[lang];return <section className="section shell" id="solutions"><div className="section-heading"><h2>{c.servicesTitle}</h2><p>{c.servicesIntro}</p></div><div className="service-grid">{c.services.map((s,i)=><Link className={`service-card service-${i}`} href={href(lang,serviceRoutes[i])} key={s.tag}><div className="card-top"><span className="index">0{i+1}</span><span aria-hidden="true">↗</span></div><p className="eyebrow">{s.label}</p><h3>{s.tag}</h3><p>{s.description}</p><span className="card-link">{c.discover} <span aria-hidden="true">→</span></span></Link>)}</div></section>}
export function Approach({c}: {c: Copy}) {return <section className="approach"><div className="shell"><p className="eyebrow">{c.approachLabel}</p><h2>{c.approachTitle}</h2><div className="steps">{c.steps.map(([title,text],i)=><div key={title}><span className="index">0{i+1}</span><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>}
export function About({lang,full=false}: {lang: Locale; full?: boolean}) {const c=content[lang];return <section className="section shell about-grid"><div className="about-image"><Image src="/images/hong-kong-skyline.jpg" alt={c.photo} width={900} height={700} sizes="(max-width: 760px) 100vw, 50vw"/><span>{c.city}</span></div><div><p className="eyebrow">{c.aboutLabel}</p>{full?<h1>{c.aboutTitle}</h1>:<h2>{c.aboutTitle}</h2>}<p className="body-large">{c.aboutText}</p><Link className="text-link" href={href(lang,full?'contact':'about')}>{full?c.nav[4]:c.aboutMore} <span aria-hidden="true">↗</span></Link></div></section>}
export function ContactBand({lang}: {lang: Locale}) {const c=content[lang];return <section className="contact-band"><div className="shell"><h2>{c.contactTitle}</h2><Link className="button light" href={href(lang,'contact')}>{c.nav[4]} <span aria-hidden="true">↗</span></Link></div></section>}
export function Home({lang}: {lang: Locale}) {const c=content[lang];return <><section className="hero"><div className="shell"><div className="hero-topline"><p className="eyebrow">{c.eyebrow}</p><span className="hero-mark" aria-hidden="true">↗</span></div><h1>{c.hero}<br/><span>{c.accent}</span></h1><div className="hero-bottom"><p>{c.sub}</p><a className="button" href="#solutions">{c.explore} <span aria-hidden="true">↓</span></a></div><div className="hero-index" aria-hidden="true"><span>01 / SOFTWARE</span><span>02 / ERP</span><span>03 / AI</span></div></div></section><ServiceGrid lang={lang}/><Approach c={c}/><About lang={lang}/><ContactBand lang={lang}/></>}
export function ServicePage({lang,index}: {lang:Locale;index:number}) {const c=content[lang],s=c.services[index];return <><section className="detail-hero shell"><Link className="back-link" href={href(lang)} >← {c.back}</Link><p className="eyebrow">0{index+1} / {s.tag}</p><h1>{s.title}</h1><p className="body-large">{s.intro}</p><a className="button" href={`${href(lang,'contact')}#contact-topic`}>{s.cta} <span aria-hidden="true">↗</span></a></section>{index===0&&<aside className="early-note shell"><span className="status-dot"/><div><strong>{c.early}</strong><p>{c.earlyText}</p></div></aside>}<section className="features shell">{s.features.map(([title,text],i)=><article key={title}><span className="index">0{i+1}</span><div><h2>{title}</h2><p>{text}</p></div></article>)}</section><Approach c={c}/><ContactBand lang={lang}/></>}
export function ContactPage({lang}: {lang:Locale}) {const c=content[lang];return <section className="contact-page shell"><div><p className="eyebrow">AKEMIS / {c.nav[4]}</p><h1>{c.contactTitle}</h1><p className="body-large">{c.contactText}</p><a className="email-address" href="mailto:contact@akemis.com">contact@akemis.com ↗</a><p className="contact-hint">{c.contactHint}</p></div><ContactForm lang={lang} topics={c.contactTopics}/></section>}
