export const locales = ['en', 'es', 'fr'] as const;
export type Locale = typeof locales[number];
export const routes = ['', 'freelancers', 'consulting', 'ai', 'about', 'contact'] as const;
export type Route = typeof routes[number];
export const isLocale = (value: string): value is Locale => locales.includes(value as Locale);
export type Service = { label: string; title: string; description: string; tag: string; intro: string; features: [string, string][]; cta: string };
export type Copy = {
  nav: string[]; menu: string; language: string; skip: string; eyebrow: string; hero: string; accent: string; sub: string; explore: string;
  servicesTitle: string; servicesIntro: string; discover: string; services: Service[];
  approachLabel: string; approachTitle: string; steps: [string, string][];
  aboutLabel: string; aboutTitle: string; aboutText: string; aboutMore: string; city: string;
  contactTitle: string; contactText: string; email: string; contactHint: string; contactTopics: string[];
  footer: string; legal: string; early: string; earlyText: string; back: string; photo: string;
};
export const content: Record<Locale, Copy> = {
 en: {
  nav: ['Freelancer software', 'Consulting & ERP', 'AI solutions', 'About', 'Let’s talk'], menu: 'Menu', language: 'Language', skip: 'Skip to content',
  eyebrow: 'AKEMIS · HONG KONG · SINCE 2003', hero: 'Less friction.', accent: 'More possibility.',
  sub: 'Software for independent professionals. Connected enterprise systems. AI ideas turned into working products.', explore: 'Find your solution',
  servicesTitle: 'Three ways to move forward.', servicesIntro: 'For the work you do today. And the business you want to build next.', discover: 'Explore',
  services: [
   {label:'For independent professionals', title:'Your work. Your invoices. Less admin.', description:'Invoicing software shaped by the everyday needs of freelance consultants.', tag:'Freelancer software', intro:'Good work deserves simpler administration. We’re developing a freelancer product from Akemis Ledger, our invoicing and reconciliation platform, to help independent professionals keep clients, invoices and payments in view.', features:[['Invoicing, with clarity','Create and follow invoices across clients and currencies. Keep billing details and invoice history together.'],['A clearer view of payments','Bring invoices and incoming payments into the same workflow, with reconciliation at the centre.'],['Built from real workflows','Our existing Ledger platform brings together invoicing, bank transactions, contracts and a consultant portal.'],['A product taking shape','The independent software offer is in development. Talk to us about your workflow and early access.']], cta:'Ask about early access'},
   {label:'For businesses & project teams', title:'Make your systems work together.', description:'Consulting and ERP integration grounded in business processes and delivery experience.', tag:'Consulting & ERP', intro:'An ERP project is a business project. We help you understand the process, connect the systems and deliver changes that the people running your business can actually use.', features:[['Process & solution design','Map the current workflow, identify the constraints and turn business needs into a practical delivery scope.'],['ERP integration','Connect enterprise applications, data and surrounding tools, drawing on experience with SAP and Oracle PeopleSoft.'],['Project delivery','Support implementation, migration and coordination across business stakeholders and technical teams.'],['Adoption & continuity','Plan testing, handover and operational support so the solution continues to work after launch.']], cta:'Discuss your integration project'},
   {label:'For teams ready to build', title:'From AI idea to useful software.', description:'Rapid development of applications, internal tools and AI-powered workflows.', tag:'AI solutions', intro:'Start with a real business problem. We use AI-assisted development to turn a focused idea into working software, then test it against the workflow it needs to improve.', features:[['Rapid prototypes','Explore a specific use case with a working prototype before committing to a larger build.'],['Custom applications','Build internal tools and focused web applications around your team’s processes.'],['AI in your workflow','Apply AI to document processing, knowledge retrieval and repetitive tasks, with human review where it matters.'],['Connected by design','Integrate with existing systems and define access, evaluation and handover as part of the project.']], cta:'Tell us what you want to build'}
  ],
  approachLabel:'HOW WE WORK', approachTitle:'Business first. Then the right technology.', steps:[['Understand','Start with the people, the process and the problem worth solving.'],['Build','Define a focused scope and make progress visible through working software.'],['Connect','Fit the solution into your business, with testing and a clear handover.']],
  aboutLabel:'THE EXPERIENCE BEHIND THE WORK', aboutTitle:'Enterprise roots. An independent mindset.', aboutText:'Established in Hong Kong in 2003, Akemis brings enterprise consulting experience to the way businesses work today. We connect that experience with practical software development: from freelance invoicing to ERP integration and AI solutions.', aboutMore:'Meet Akemis', city:'Hong Kong / Working across borders',
  contactTitle:'What would you like to move forward?', contactText:'Tell us where you are today and what you want to change. We’ll start with a conversation.', email:'Email Akemis', contactHint:'Email opens in your mail app. Include your current tools, the outcome you need and any timing constraints.', contactTopics:['Freelancer software & early access','Consulting & ERP integration','AI applications & automation'], footer:'Software. Systems. Possibility.', legal:'Creator app legal', early:'In development · Early-access enquiries', earlyText:'The freelancer SaaS is being developed from Ledger. Features and availability will be confirmed before onboarding. Managed contracting is a separate service; contact us to discuss your needs.', back:'All solutions', photo:'Hong Kong skyline and Victoria Harbour'
 },
 es: {
  nav:['Software para independientes','Consultoría y ERP','Soluciones de IA','Nosotros','Hablemos'],menu:'Menú',language:'Idioma',skip:'Ir al contenido',
  eyebrow:'AKEMIS · HONG KONG · DESDE 2003',hero:'Menos obstáculos.',accent:'Más posibilidades.',sub:'Software para profesionales independientes. Sistemas empresariales conectados. Ideas de IA convertidas en productos útiles.',explore:'Encuentra tu solución',
  servicesTitle:'Tres formas de avanzar.',servicesIntro:'Para tu trabajo de hoy. Y para el negocio que quieres construir mañana.',discover:'Descubrir',
  services:[
   {label:'Para profesionales independientes',title:'Tu trabajo. Tus facturas. Menos gestión.',description:'Software de facturación pensado para el día a día de los consultores independientes.',tag:'Software para independientes',intro:'Un buen trabajo merece una gestión más sencilla. Estamos desarrollando un producto para profesionales independientes a partir de Akemis Ledger, nuestra plataforma de facturación y conciliación, para reunir clientes, facturas y pagos.',features:[['Facturación clara','Crea y sigue facturas de distintos clientes y en varias divisas. Reúne los datos de facturación y el historial.'],['Una visión más clara de los pagos','Conecta las facturas y los pagos recibidos en un mismo flujo de trabajo, con la conciliación como pieza central.'],['Basado en procesos reales','Nuestra plataforma Ledger reúne facturación, movimientos bancarios, contratos y un portal para consultores.'],['Un producto en desarrollo','La oferta de software para independientes está en desarrollo. Cuéntanos cómo trabajas y consulta el acceso anticipado.']],cta:'Consultar el acceso anticipado'},
   {label:'Para empresas y equipos de proyecto',title:'Haz que tus sistemas trabajen juntos.',description:'Consultoría e integración de ERP basadas en procesos de negocio y experiencia de ejecución.',tag:'Consultoría y ERP',intro:'Un proyecto de ERP es un proyecto de negocio. Te ayudamos a entender los procesos, conectar los sistemas y entregar cambios útiles para las personas que hacen funcionar tu empresa.',features:[['Procesos y diseño de soluciones','Analizamos el flujo actual, identificamos las limitaciones y convertimos las necesidades en un alcance práctico.'],['Integración de ERP','Conectamos aplicaciones empresariales, datos y herramientas, con experiencia en SAP y Oracle PeopleSoft.'],['Ejecución de proyectos','Apoyamos la implantación, la migración y la coordinación entre los responsables de negocio y los equipos técnicos.'],['Adopción y continuidad','Planificamos las pruebas, el traspaso y el soporte operativo para que la solución siga funcionando tras el lanzamiento.']],cta:'Hablemos de tu integración'},
   {label:'Para equipos listos para crear',title:'De una idea de IA a software útil.',description:'Desarrollo rápido de aplicaciones, herramientas internas y flujos de trabajo con IA.',tag:'Soluciones de IA',intro:'Partimos de un problema de negocio concreto. Utilizamos el desarrollo asistido por IA para convertir una idea bien definida en software funcional y probarlo en el proceso que debe mejorar.',features:[['Prototipos rápidos','Explora un caso de uso específico con un prototipo funcional antes de invertir en un desarrollo mayor.'],['Aplicaciones a medida','Creamos herramientas internas y aplicaciones web adaptadas a los procesos de tu equipo.'],['IA en tu trabajo diario','Aplicamos IA al tratamiento de documentos, la búsqueda de conocimiento y las tareas repetitivas, con revisión humana cuando es necesaria.'],['Conectado desde el principio','Integramos los sistemas existentes y definimos los accesos, la evaluación y el traspaso dentro del proyecto.']],cta:'Cuéntanos qué quieres crear'}
  ],
  approachLabel:'CÓMO TRABAJAMOS',approachTitle:'Primero el negocio. Después, la tecnología adecuada.',steps:[['Entender','Empezamos por las personas, el proceso y el problema que merece resolverse.'],['Crear','Definimos un alcance concreto y mostramos el progreso con software funcional.'],['Conectar','Integramos la solución en tu negocio, con pruebas y un traspaso claro.']],
  aboutLabel:'LA EXPERIENCIA DETRÁS DEL TRABAJO',aboutTitle:'Raíces empresariales. Espíritu independiente.',aboutText:'Fundada en Hong Kong en 2003, Akemis aporta experiencia en consultoría empresarial a la forma de trabajar de hoy. La combinamos con desarrollo práctico de software: desde la facturación para independientes hasta la integración de ERP y las soluciones de IA.',aboutMore:'Conoce Akemis',city:'Hong Kong / Trabajamos más allá de las fronteras',
  contactTitle:'¿Qué te gustaría impulsar?',contactText:'Cuéntanos dónde estás y qué quieres cambiar. Empecemos con una conversación.',email:'Escribe a Akemis',contactHint:'El enlace abre tu aplicación de correo. Incluye tus herramientas actuales, el resultado que necesitas y los plazos previstos.',contactTopics:['Software para independientes y acceso anticipado','Consultoría e integración de ERP','Aplicaciones de IA y automatización'],footer:'Software. Sistemas. Posibilidades.',legal:'Información legal de Creator',early:'En desarrollo · Consultas de acceso anticipado',earlyText:'El SaaS para independientes se está desarrollando a partir de Ledger. Las funciones y la disponibilidad se confirmarán antes del alta. La contratación gestionada es un servicio distinto; contáctanos para hablar de tus necesidades.',back:'Todas las soluciones',photo:'Vista de Hong Kong y el puerto de Victoria'
 },
 fr: {
  nav:['Logiciel pour indépendants','Conseil & ERP','Solutions IA','À propos','Parlons-en'],menu:'Menu',language:'Langue',skip:'Aller au contenu',
  eyebrow:'AKEMIS · HONG KONG · DEPUIS 2003',hero:'Moins de contraintes.',accent:'Plus de possibilités.',sub:'Des logiciels pour les indépendants. Des systèmes d’entreprise connectés. Des idées IA transformées en applications utiles.',explore:'Trouver votre solution',
  servicesTitle:'Trois façons d’avancer.',servicesIntro:'Pour votre activité d’aujourd’hui. Et celle que vous voulez construire demain.',discover:'Découvrir',
  services:[
   {label:'Pour les professionnels indépendants',title:'Votre travail. Vos factures. Moins d’administratif.',description:'Un logiciel de facturation pensé pour le quotidien des consultants indépendants.',tag:'Logiciel pour indépendants',intro:'Un travail bien fait mérite une gestion plus simple. Nous développons une offre pour les indépendants à partir d’Akemis Ledger, notre plateforme de facturation et de rapprochement, pour réunir clients, factures et paiements.',features:[['Une facturation claire','Créez et suivez les factures de vos clients dans plusieurs devises. Retrouvez les coordonnées de facturation et l’historique au même endroit.'],['Une meilleure visibilité sur les paiements','Rapprochez factures et encaissements dans un même processus, avec le rapprochement bancaire au cœur du fonctionnement.'],['Des usages réels comme point de départ','Notre plateforme Ledger réunit facturation, transactions bancaires, contrats et portail consultant.'],['Un produit en préparation','L’offre de logiciel pour indépendants est en développement. Échangeons sur vos usages et l’accès anticipé.']],cta:'Se renseigner sur l’accès anticipé'},
   {label:'Pour les entreprises et les équipes projet',title:'Faites travailler vos systèmes ensemble.',description:'Du conseil et de l’intégration ERP ancrés dans les processus métier et l’expérience terrain.',tag:'Conseil & ERP',intro:'Un projet ERP est un projet d’entreprise. Nous vous aidons à comprendre les processus, connecter les systèmes et livrer des évolutions utiles aux personnes qui font fonctionner votre activité.',features:[['Processus & conception','Analyser les pratiques actuelles, identifier les contraintes et traduire les besoins métier en un périmètre concret.'],['Intégration ERP','Connecter applications d’entreprise, données et outils, avec une expérience de SAP et d’Oracle PeopleSoft.'],['Pilotage & réalisation','Accompagner la mise en œuvre, la migration et la coordination entre les métiers et les équipes techniques.'],['Adoption & continuité','Préparer les tests, la transmission et le support opérationnel pour que la solution reste utile après son lancement.']],cta:'Parlons de votre projet d’intégration'},
   {label:'Pour les équipes prêtes à construire',title:'De l’idée IA à une application utile.',description:'Développement rapide d’applications, d’outils internes et de processus intégrant l’IA.',tag:'Solutions IA',intro:'Partons d’un problème métier concret. Nous utilisons le développement assisté par IA pour transformer une idée ciblée en logiciel fonctionnel, puis le tester dans le processus qu’il doit améliorer.',features:[['Prototypage rapide','Explorer un cas d’usage précis avec un prototype fonctionnel avant d’engager un projet plus large.'],['Applications sur mesure','Créer des outils internes et des applications web adaptés aux processus de votre équipe.'],['L’IA dans vos processus','Appliquer l’IA au traitement documentaire, à la recherche d’information et aux tâches répétitives, avec une validation humaine lorsque nécessaire.'],['L’intégration dès le départ','Connecter les systèmes existants et définir les accès, l’évaluation et la transmission dans le cadre du projet.']],cta:'Présentez-nous votre idée'}
  ],
  approachLabel:'NOTRE MÉTHODE',approachTitle:'Le métier d’abord. La technologie ensuite.',steps:[['Comprendre','Partir des personnes, du processus et du problème qui mérite d’être résolu.'],['Construire','Définir un périmètre ciblé et rendre les progrès visibles grâce à un logiciel fonctionnel.'],['Connecter','Intégrer la solution à votre activité, avec des tests et une transmission claire.']],
  aboutLabel:'L’EXPÉRIENCE AU SERVICE DU CONCRET',aboutTitle:'Une culture d’entreprise. Un esprit indépendant.',aboutText:'Fondée à Hong Kong en 2003, Akemis met son expérience du conseil en systèmes d’entreprise au service des usages d’aujourd’hui. Nous l’associons au développement de logiciels concrets : facturation pour indépendants, intégration ERP et solutions IA.',aboutMore:'Découvrir Akemis',city:'Hong Kong / Au-delà des frontières',
  contactTitle:'Que souhaitez-vous faire avancer ?',contactText:'Dites-nous où vous en êtes et ce que vous souhaitez changer. Commençons par une conversation.',email:'Écrire à Akemis',contactHint:'Le lien ouvre votre messagerie. Précisez vos outils actuels, le résultat attendu et vos contraintes de calendrier.',contactTopics:['Logiciel pour indépendants et accès anticipé','Conseil et intégration ERP','Applications IA et automatisation'],footer:'Logiciels. Systèmes. Possibilités.',legal:'Informations légales Creator',early:'En développement · Demandes d’accès anticipé',earlyText:'Le SaaS pour indépendants est en cours de développement à partir de Ledger. Les fonctionnalités et la disponibilité seront confirmées avant l’inscription. La gestion contractuelle est un service distinct ; contactez-nous pour en discuter.',back:'Toutes les solutions',photo:'Vue de Hong Kong et du port Victoria'
 }
};
export const serviceRoutes = ['freelancers','consulting','ai'] as const;
export function href(lang: Locale, route: string = '') { return `/${lang}${route ? `/${route}` : ''}`; }
export function emailLink(subject: string) { return `mailto:contact@akemis.com?subject=${encodeURIComponent(subject)}`; }
